syntax = "proto3";

package game;

// Enums
enum RcvStatus {
    DISCONNECTED = 0;
    WOULDBLOCK = 1;
    PARSE_ERROR = 2;
    OK = 3;
}

enum CommandType {
    INTERACTION_COMMAND = 0;
    ATTACK_COMMAND = 1;
    MESSAGE_COMMAND = 2;
    INVALID_COMMAND = 3;
}

enum InteractionType {
    MOVE = 0;
    PICK_UP = 1;
    DROP = 2;
    OPEN = 3;
    SPEAK = 4;
    ATTACK = 5;
    USE = 6;
    SELL = 7;
    GIVE = 8;
}

enum PlayerState {
    CHILLING = 0;
    IN_COMBAT = 1;
    DEAD = 2;
}

enum CombatAction {
    LIGHT_ATTACK = 0;
    STRONG_ATTACK = 1;
    CONCENTRATE = 2;
    FLEE = 3;
    HALF_DEFEND = 4;
    FULL_DEFEND = 5;
    COUNTER = 6;
    NONE = 7;
}

enum Direction {
    NORTH = 0;
    EAST = 1;
    WEST = 2;
    SOUTH = 3;
}

enum EffectType {
    HEAL = 0;
    DAMAGE = 1;
    ENERGY_BUFF = 2;
    ENERGY_DEBUFF = 3;
    KEY = 4;
}

enum Temperament {
    PASSIVE = 0;
    DEFENSIVE = 1;
    AGGRESIVE = 2;
}

enum Usage {
    SELF = 0;
    OTHER = 1;
    HYBRID = 2;
    WORLD = 3;
}

// Structures de données
message Effect
{
    EffectType type = 1;
    uint32 amount = 2;
}

message Spawn
{
    string npc_type = 1;
    uint64 amount = 2;
}

message Item
{
    uint64 id = 1;
    string display_name = 2;
    string full_name = 3;
    string description = 4;
    bool is_obtainable = 5;
    repeated Effect effects = 6;
    Usage usage = 7;
}

message Exit
{
    Direction direction = 1;
    uint64 location_id = 2;
    bool is_locked = 3;
    uint64 unlock_item_id = 4;
}

message Location
{
    uint64 id = 1;
    string name = 2;
    string description = 3;
    repeated Exit exits = 4;
    repeated Spawn spawns = 5;
    repeated uint64 item_ids = 6;
}

message Npc
{
    uint64 id = 1;
    string type = 2;
    string name = 3;
    string description = 4;
    repeated string dialogues = 5;
    bool can_trade = 6;
    map<uint64, uint64> inventory = 7; // <ItemId, Quantity>
    map<uint64, uint64> trade_inventory =
        8; // <ItemId, Price> (Items can only be the ones in the main inventory)
    uint32 hp = 9;
    Temperament temperament = 10;
}

message Player
{
    uint64 id = 1;
    string name = 2;
    uint32 hp = 3;
    repeated uint64 inventory = 4; // list of item ids
    PlayerState state = 5;
    uint64 money_amount = 6;
}

message World
{
    repeated Item items = 1;
    repeated Npc npcs = 2;
    repeated Location locations = 3;
    uint64 start_location_id = 4;
    map<uint64, uint64> players = 5; // <player id, location id>
}

// Message pour les deltas (mises à jour partielles du monde)
message WorldDelta
{
    oneof delta_type
    { // 'oneof' est l'équivalent Protobuf de std::variant
        PlayerInventoryChanged player_inventory_changed = 1; //
        NpcInventoryChanged npc_inventory_changed = 2;
        PlayerHpChanged player_hp_changed = 3;
        NpcHpChanged npc_hp_changed = 4;
        PlayerMoved player_moved = 5;
        NpcMoved npc_moved = 6;
        DoorUnlock door_unlock = 7;
        PlayerStateChanged player_state_changed = 8;
        MessageReceived message_received = 9;

        // WHEN CONNECTING TO SERVER
        InitWorld world_initiation = 10;
        PlayerConnected player_connected = 11;
        PlayerDisconnected player_disconnected = 12;
        UnauthorizedCommand unauthorized_command = 13;
    }
}

message MessageReceived
{
    uint64 player_id = 1;
    string message = 2;
}

message UnauthorizedCommand
{
    string response = 1;
}

message PlayerConnected
{
    uint64 player_id = 1;
    string player_name = 2;
}

message PlayerDisconnected
{
    uint64 player_id = 1;
}

message PlayerInventoryChanged
{
    uint64 player_id = 1;
    uint64 item_id = 2;
    InteractionType Interaction = 3; // USE, DROP, PICKUP
}

message NpcInventoryChanged
{
    uint64 npc_id = 1;
    uint64 item_id = 2;
    InteractionType Interaction = 3; // USE, SELL, GIVE
}

message PlayerHpChanged
{
    uint64 player_id = 1;
    uint32 new_hp = 2;
}

message NpcHpChanged
{
    uint64 npc_id = 1;
    uint32 new_hp = 2;
}

message PlayerMoved
{
    uint64 player_id = 1;
    uint64 new_location_id = 2;
}

message NpcMoved
{
    uint64 npc_id = 1;
    uint64 new_location_id = 2;
}

message DoorUnlock
{                         // When unlocking a door:
    uint64 exit_id = 1;   // 1. Server checks if the user has the correct item
    uint64 player_id = 2; // 2. server sends a PlayerInventoryChanged to use the item
} // 3. server send a DoorUnlock to unlock the door

message PlayerStateChanged
{
    uint64 player_id = 1;
    PlayerState new_state = 2;
}

message InitWorld
{
    repeated Item items = 1;
    repeated Npc npcs = 2;
    repeated Location locations = 3;
    uint64 start_location_id = 4;
}

message CommandDelta
{
    oneof delta_type
    { // 'oneof' est l'équivalent Protobuf de std::variant !
        InteractionCommand interaction_command = 1;
        AttackCommand attack_command = 2;
        MessageCommand message_command = 3;
    }
}

message InteractionCommand
{
    InteractionType type = 1;
    uint64 target_id = 2;
}

message AttackCommand
{
    CombatAction action = 1;
}

message MessageCommand
{
    string message = 1;
}
